# Generated by Django 3.2.16 on 2025-12-19 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ice_cream', '0003_auto_20251216_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
    ]
